//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyAtHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAH_Payment
    {
        public int ID { get; set; }
        public int PaymentTypeID { get; set; }
        public string CardNumber { get; set; }
        public int BillingAddressID { get; set; }
        public string NameOnCard { get; set; }
        public int ExpirationMonth { get; set; }
        public int ExpirationYear { get; set; }
        public int CvcCode { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DAH_Address DAH_Address { get; set; }
        public virtual DAH_PaymentType DAH_PaymentType { get; set; }
    }
}
