//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyAtHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAH_Products
    {
        public int ID { get; set; }
        public string Product { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public decimal Cost { get; set; }
        public int SubCategoryID { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual DAH_SubCategories DAH_SubCategories { get; set; }
    }
}
