//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyAtHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAH_Img_Categories
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual DAH_Categories DAH_Categories { get; set; }
    }
}
