//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyAtHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAH_Img_SubCategories
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
    
        public virtual DAH_SubCategories DAH_SubCategories { get; set; }
    }
}
