//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyAtHome.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dahDBEntities : DbContext
    {
        public dahDBEntities()
            : base("name=dahDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DAH_Img_Categories> DAH_Img_Categories { get; set; }
        public virtual DbSet<DAH_Img_Products> DAH_Img_Products { get; set; }
        public virtual DbSet<DAH_Img_SubCategories> DAH_Img_SubCategories { get; set; }
        public virtual DbSet<DAH_Categories> DAH_Categories { get; set; }
        public virtual DbSet<DAH_SubCategories> DAH_SubCategories { get; set; }
        public virtual DbSet<DAH_Products> DAH_Products { get; set; }
    }
}
