//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyAtHome.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategory
    {
        public int id { get; set; }
        public string subcategory1 { get; set; }
        public Nullable<int> categoryid { get; set; }
    
        public virtual category category { get; set; }
    }
}
